<?php

require_once __DIR__.'/Support/ContractTable.php';

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\URL;
use Musing\InertiaTable\Tests\Support\ContractTopicRecord;
use Musing\InertiaTable\Tests\Support\ContractTopicsCursorTable;
use Musing\InertiaTable\Tests\Support\ContractTopicsSimpleTable;
use Musing\InertiaTable\Tests\Support\ContractTopicsTable;
use Musing\InertiaTable\Tests\Support\ContractTopicsUnpaginatedTable;

const CONTRACT_FIXTURE_PATH = __DIR__.'/../tests-js/contracts/resource.generated.ts';

beforeEach(function () {
    config()->set('app.url', 'https://contract.test');
    URL::forceRootUrl('https://contract.test');

    Schema::create('contract_topics', function (Blueprint $table) {
        $table->id();
        $table->string('name');
        $table->string('status');
        $table->unsignedInteger('amount');
    });
    $migration = require dirname(__DIR__).'/database/migrations/create_table_views_table.php.stub';
    $migration->up();

    ContractTopicRecord::query()->insert([
        ['name' => 'Alpha', 'status' => 'open', 'amount' => 10],
        ['name' => 'Beta', 'status' => 'closed', 'amount' => 20],
    ]);
});

function contractRequest(array $state = []): Request
{
    return Request::create('/contract-topics', 'GET', [
        'table' => ['contract_topics' => $state],
    ]);
}

/** @return array<string, array<string, mixed>> */
function contractResources(): array
{
    $fullTable = new ContractTopicsTable;
    $request = contractRequest();
    $views = $fullTable->views();
    expect($views)->not->toBeNull();
    $view = $views->newQuery()->create($views->valuesFor(
        $fullTable,
        $request,
        'Contract default',
        ['sort' => 'name'],
    ));
    $view->forceFill(['is_default' => true])->save();

    return [
        'full' => $fullTable->resolve($request)->toArray(),
        'simple' => (new ContractTopicsSimpleTable)->resolve(contractRequest())->toArray(),
        'cursor' => (new ContractTopicsCursorTable)->resolve(contractRequest())->toArray(),
        'unpaginated' => (new ContractTopicsUnpaginatedTable)->resolve(contractRequest())->toArray(),
    ];
}

/** @param array<string, array<string, mixed>> $resources */
function contractFixtureContents(array $resources): string
{
    $resourcesJson = json_encode(
        $resources,
        JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR,
    );

    return <<<TS
        /* This file is generated by tests/ContractResourceTest.php. Do not edit manually. */
        import type { TableItem, TableResource } from "../../resources/js/types";

        export type ContractTopic = TableItem & {
            id: number;
            name: string;
            status: string;
            amount: number;
        };

        const resources = {$resourcesJson} satisfies Record<
            "full" | "simple" | "cursor" | "unpaginated",
            TableResource<ContractTopic>
        >;

        export const contractResource = resources.full;
        export const contractSimpleResource = resources.simple;
        export const contractCursorResource = resources.cursor;
        export const contractUnpaginatedResource = resources.unpaginated;
        TS;
}

it('keeps the generated TypeScript table contract fixture current', function () {
    $contents = contractFixtureContents(contractResources());
    $updating = getenv('INERTIA_TABLE_UPDATE_CONTRACTS') === '1';

    if ($updating) {
        if (getenv('CI') !== false) {
            throw new LogicException('Contract fixtures cannot be updated in CI.');
        }

        file_put_contents(CONTRACT_FIXTURE_PATH, $contents);
    }

    expect(file_get_contents(CONTRACT_FIXTURE_PATH))->toBe($contents);
});
