/* This file is generated by tests/ContractResourceTest.php. Do not edit manually. */
import type { TableItem, TableResource } from "../../resources/js/types";

export type ContractTopic = TableItem & {
    id: number;
    name: string;
    status: string;
    amount: number;
    is_featured: boolean;
    published_at: string;
};

const resources = {
    "full": {
        "schemaVersion": 2,
        "name": "contract_topics",
        "columns": [
            {
                "attribute": "name",
                "header": "Name",
                "type": "text",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 240,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "amount",
                "header": "Amount",
                "type": "numeric",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 160,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": {
                    "type": "sum",
                    "format": null
                },
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "status",
                "header": "Status",
                "type": "badge",
                "sortable": false,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": null,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            }
        ],
        "filters": [
            {
                "attribute": "status",
                "label": "Status",
                "clauses": [
                    "in",
                    "not_in",
                    "equals",
                    "not_equals"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "set",
                "options": [
                    {
                        "value": "open",
                        "label": "Open"
                    },
                    {
                        "value": "closed",
                        "label": "Closed"
                    }
                ],
                "multiple": true
            },
            {
                "attribute": "amount",
                "label": "Amount",
                "clauses": [
                    "equals",
                    "not_equals",
                    "greater_than",
                    "greater_than_or_equal",
                    "less_than",
                    "less_than_or_equal",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "numeric",
                "options": []
            },
            {
                "attribute": "published_at",
                "label": "Published at",
                "clauses": [
                    "before",
                    "after",
                    "equal_or_before",
                    "equal_or_after",
                    "equals",
                    "not_equals",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "date",
                "options": []
            },
            {
                "attribute": "is_featured",
                "label": "Featured",
                "clauses": [
                    "is_true",
                    "is_false"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "boolean",
                "options": []
            }
        ],
        "actions": [
            {
                "key": "archive",
                "label": "Archive",
                "scope": "bulk",
                "authorized": true,
                "disabled": false,
                "hidden": false,
                "variant": "default",
                "icon": null,
                "labelHidden": false,
                "tooltip": null,
                "buttonClass": null,
                "disabledTooltip": null,
                "confirmation": null,
                "endpoint": {
                    "method": "post",
                    "url": "/contract-topics/archive"
                },
                "meta": []
            }
        ],
        "search": [
            "name"
        ],
        "capabilities": {
            "searchable": true,
            "selectable": true,
            "paginated": true,
            "hasSearch": true,
            "hasFilters": true,
            "hasActions": true,
            "hasBulkActions": true,
            "hasExports": true,
            "hasToggleableColumns": true,
            "hasStickableColumns": true,
            "hasResizableColumns": true,
            "hasReorderableColumns": true,
            "hasSummaries": true,
            "hasEmptyState": false
        },
        "state": {
            "search": "",
            "sort": "name",
            "filters": {
                "status": {
                    "enabled": false,
                    "clause": "in",
                    "value": null
                },
                "amount": {
                    "enabled": false,
                    "clause": "equals",
                    "value": null
                },
                "published_at": {
                    "enabled": false,
                    "clause": "before",
                    "value": null
                },
                "is_featured": {
                    "enabled": false,
                    "clause": "is_true",
                    "value": null
                }
            },
            "columns": {
                "name": true,
                "amount": true,
                "status": true
            },
            "page": 1,
            "perPage": 1,
            "view": 1,
            "pinnedColumns": {
                "left": [],
                "right": []
            },
            "cursor": null,
            "columnOrder": [
                "name",
                "amount",
                "status"
            ],
            "columnWidths": {
                "name": 240,
                "amount": 160
            }
        },
        "results": {
            "data": [
                {
                    "id": 1,
                    "name": "Alpha",
                    "status": "open",
                    "amount": 10,
                    "is_featured": false,
                    "published_at": "2025-01-10T00:00:00.000000Z",
                    "_table": {
                        "key": 1,
                        "selectable": true,
                        "url": null,
                        "columns": [],
                        "cells": {
                            "status": {
                                "variant": "success",
                                "icon": null,
                                "badgeClass": null
                            }
                        },
                        "actions": [],
                        "dataAttributes": []
                    }
                }
            ],
            "currentPage": 1,
            "from": 1,
            "lastPage": 2,
            "links": [
                {
                    "url": null,
                    "label": "&laquo; Previous",
                    "active": false
                },
                {
                    "url": "http://localhost?table%5Bcontract_topics%5D%5Bpage%5D=1",
                    "label": "1",
                    "active": true
                },
                {
                    "url": "http://localhost?table%5Bcontract_topics%5D%5Bpage%5D=2",
                    "label": "2",
                    "active": false
                },
                {
                    "url": "http://localhost?table%5Bcontract_topics%5D%5Bpage%5D=2",
                    "label": "Next &raquo;",
                    "active": false
                }
            ],
            "perPage": 1,
            "to": 1,
            "total": 2,
            "selectableTotal": 2,
            "hasPreviousPage": false,
            "hasNextPage": true,
            "previousCursor": null,
            "nextCursor": null
        },
        "options": {
            "debounceTime": 300,
            "perPage": [
                1,
                2
            ],
            "paginationType": "full",
            "reloadProps": [],
            "stickyHeader": false,
            "stickyFooter": false,
            "stickyBackdropFilter": true,
            "columnResizing": true,
            "columnReordering": true
        },
        "views": {
            "items": [
                {
                    "id": 1,
                    "name": "Contract default",
                    "state": {
                        "schemaVersion": 2,
                        "sort": "name",
                        "filters": {
                            "status": {
                                "enabled": false,
                                "clause": "in",
                                "value": null
                            },
                            "amount": {
                                "enabled": false,
                                "clause": "equals",
                                "value": null
                            },
                            "published_at": {
                                "enabled": false,
                                "clause": "before",
                                "value": null
                            },
                            "is_featured": {
                                "enabled": false,
                                "clause": "is_true",
                                "value": null
                            }
                        },
                        "columns": {
                            "name": true,
                            "amount": true,
                            "status": true
                        },
                        "pinnedColumns": {
                            "left": [],
                            "right": []
                        },
                        "columnOrder": [
                            "name",
                            "amount",
                            "status"
                        ],
                        "columnWidths": {
                            "name": 240,
                            "amount": 160
                        },
                        "perPage": 1
                    },
                    "isDefault": true,
                    "isShared": true,
                    "version": 0,
                    "canUpdate": true,
                    "canDelete": true,
                    "canShare": false,
                    "canDefault": true,
                    "endpoints": {
                        "update": "/_inertia-table/views/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzVGFibGU/1?signature=baf5b4e8c9404691afa5616686fbe2a3d46733e735c2d56e03ec51c22ce4e0c6",
                        "delete": "/_inertia-table/views/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzVGFibGU/1?signature=baf5b4e8c9404691afa5616686fbe2a3d46733e735c2d56e03ec51c22ce4e0c6",
                        "default": "/_inertia-table/views/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzVGFibGU/1/default?signature=f1017b4aea62fec3ef74b6897c5ffe3a2641e4d2f0f09db4c886816691d760bb",
                        "share": null
                    }
                }
            ],
            "selected": 1,
            "includeSearch": false,
            "canCreate": true,
            "storeEndpoint": "/_inertia-table/views/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzVGFibGU?signature=4797fcd881825b38b21980cfb4754f8c66a29bf958754a44436119bb01110824"
        },
        "exports": [
            {
                "key": "csv",
                "label": "Contract CSV",
                "filename": "contract-topics.csv",
                "type": "csv",
                "scope": "filtered",
                "requiresSelection": false,
                "queued": false,
                "includesSummaries": true,
                "endpoint": "/_inertia-table/exports/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzVGFibGU/csv?signature=6e420f4315be43112a342734ed8a6b633ac5d6bcbe49c04b1687fde6d7a37f52",
                "meta": []
            }
        ],
        "emptyState": null,
        "summaries": {
            "amount": 30
        }
    },
    "simple": {
        "schemaVersion": 2,
        "name": "contract_topics",
        "columns": [
            {
                "attribute": "name",
                "header": "Name",
                "type": "text",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 240,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "amount",
                "header": "Amount",
                "type": "numeric",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 160,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": {
                    "type": "sum",
                    "format": null
                },
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "status",
                "header": "Status",
                "type": "badge",
                "sortable": false,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": null,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            }
        ],
        "filters": [
            {
                "attribute": "status",
                "label": "Status",
                "clauses": [
                    "in",
                    "not_in",
                    "equals",
                    "not_equals"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "set",
                "options": [
                    {
                        "value": "open",
                        "label": "Open"
                    },
                    {
                        "value": "closed",
                        "label": "Closed"
                    }
                ],
                "multiple": true
            },
            {
                "attribute": "amount",
                "label": "Amount",
                "clauses": [
                    "equals",
                    "not_equals",
                    "greater_than",
                    "greater_than_or_equal",
                    "less_than",
                    "less_than_or_equal",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "numeric",
                "options": []
            },
            {
                "attribute": "published_at",
                "label": "Published at",
                "clauses": [
                    "before",
                    "after",
                    "equal_or_before",
                    "equal_or_after",
                    "equals",
                    "not_equals",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "date",
                "options": []
            },
            {
                "attribute": "is_featured",
                "label": "Featured",
                "clauses": [
                    "is_true",
                    "is_false"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "boolean",
                "options": []
            }
        ],
        "actions": [
            {
                "key": "archive",
                "label": "Archive",
                "scope": "bulk",
                "authorized": true,
                "disabled": false,
                "hidden": false,
                "variant": "default",
                "icon": null,
                "labelHidden": false,
                "tooltip": null,
                "buttonClass": null,
                "disabledTooltip": null,
                "confirmation": null,
                "endpoint": {
                    "method": "post",
                    "url": "/contract-topics/archive"
                },
                "meta": []
            }
        ],
        "search": [
            "name"
        ],
        "capabilities": {
            "searchable": true,
            "selectable": true,
            "paginated": true,
            "hasSearch": true,
            "hasFilters": true,
            "hasActions": true,
            "hasBulkActions": true,
            "hasExports": true,
            "hasToggleableColumns": true,
            "hasStickableColumns": true,
            "hasResizableColumns": true,
            "hasReorderableColumns": true,
            "hasSummaries": true,
            "hasEmptyState": false
        },
        "state": {
            "search": "",
            "sort": "name",
            "filters": {
                "status": {
                    "enabled": false,
                    "clause": "in",
                    "value": null
                },
                "amount": {
                    "enabled": false,
                    "clause": "equals",
                    "value": null
                },
                "published_at": {
                    "enabled": false,
                    "clause": "before",
                    "value": null
                },
                "is_featured": {
                    "enabled": false,
                    "clause": "is_true",
                    "value": null
                }
            },
            "columns": {
                "name": true,
                "amount": true,
                "status": true
            },
            "page": 1,
            "perPage": 1,
            "view": null,
            "pinnedColumns": {
                "left": [],
                "right": []
            },
            "cursor": null,
            "columnOrder": [
                "name",
                "amount",
                "status"
            ],
            "columnWidths": {
                "name": 240,
                "amount": 160
            }
        },
        "results": {
            "data": [
                {
                    "id": 1,
                    "name": "Alpha",
                    "status": "open",
                    "amount": 10,
                    "is_featured": false,
                    "published_at": "2025-01-10T00:00:00.000000Z",
                    "_table": {
                        "key": 1,
                        "selectable": true,
                        "url": null,
                        "columns": [],
                        "cells": {
                            "status": {
                                "variant": "success",
                                "icon": null,
                                "badgeClass": null
                            }
                        },
                        "actions": [],
                        "dataAttributes": []
                    }
                }
            ],
            "currentPage": 1,
            "from": 1,
            "lastPage": null,
            "links": [],
            "perPage": 1,
            "to": 1,
            "total": null,
            "selectableTotal": 2,
            "hasPreviousPage": false,
            "hasNextPage": true,
            "previousCursor": null,
            "nextCursor": null
        },
        "options": {
            "debounceTime": 300,
            "perPage": [
                1,
                2
            ],
            "paginationType": "simple",
            "reloadProps": [],
            "stickyHeader": false,
            "stickyFooter": false,
            "stickyBackdropFilter": true,
            "columnResizing": true,
            "columnReordering": true
        },
        "views": null,
        "exports": [
            {
                "key": "csv",
                "label": "Contract CSV",
                "filename": "contract-topics.csv",
                "type": "csv",
                "scope": "filtered",
                "requiresSelection": false,
                "queued": false,
                "includesSummaries": true,
                "endpoint": "/_inertia-table/exports/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzU2ltcGxlVGFibGU/csv?signature=c5f2ee4f8bcd853fbf7019c7d398268ac0e7b0f76c0eb8c1b294b24ef9c5342c",
                "meta": []
            }
        ],
        "emptyState": null,
        "summaries": {
            "amount": 30
        }
    },
    "cursor": {
        "schemaVersion": 2,
        "name": "contract_topics",
        "columns": [
            {
                "attribute": "name",
                "header": "Name",
                "type": "text",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 240,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "amount",
                "header": "Amount",
                "type": "numeric",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 160,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": {
                    "type": "sum",
                    "format": null
                },
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "status",
                "header": "Status",
                "type": "badge",
                "sortable": false,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": null,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            }
        ],
        "filters": [
            {
                "attribute": "status",
                "label": "Status",
                "clauses": [
                    "in",
                    "not_in",
                    "equals",
                    "not_equals"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "set",
                "options": [
                    {
                        "value": "open",
                        "label": "Open"
                    },
                    {
                        "value": "closed",
                        "label": "Closed"
                    }
                ],
                "multiple": true
            },
            {
                "attribute": "amount",
                "label": "Amount",
                "clauses": [
                    "equals",
                    "not_equals",
                    "greater_than",
                    "greater_than_or_equal",
                    "less_than",
                    "less_than_or_equal",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "numeric",
                "options": []
            },
            {
                "attribute": "published_at",
                "label": "Published at",
                "clauses": [
                    "before",
                    "after",
                    "equal_or_before",
                    "equal_or_after",
                    "equals",
                    "not_equals",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "date",
                "options": []
            },
            {
                "attribute": "is_featured",
                "label": "Featured",
                "clauses": [
                    "is_true",
                    "is_false"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "boolean",
                "options": []
            }
        ],
        "actions": [
            {
                "key": "archive",
                "label": "Archive",
                "scope": "bulk",
                "authorized": true,
                "disabled": false,
                "hidden": false,
                "variant": "default",
                "icon": null,
                "labelHidden": false,
                "tooltip": null,
                "buttonClass": null,
                "disabledTooltip": null,
                "confirmation": null,
                "endpoint": {
                    "method": "post",
                    "url": "/contract-topics/archive"
                },
                "meta": []
            }
        ],
        "search": [
            "name"
        ],
        "capabilities": {
            "searchable": true,
            "selectable": true,
            "paginated": true,
            "hasSearch": true,
            "hasFilters": true,
            "hasActions": true,
            "hasBulkActions": true,
            "hasExports": true,
            "hasToggleableColumns": true,
            "hasStickableColumns": true,
            "hasResizableColumns": true,
            "hasReorderableColumns": true,
            "hasSummaries": true,
            "hasEmptyState": false
        },
        "state": {
            "search": "",
            "sort": "name",
            "filters": {
                "status": {
                    "enabled": false,
                    "clause": "in",
                    "value": null
                },
                "amount": {
                    "enabled": false,
                    "clause": "equals",
                    "value": null
                },
                "published_at": {
                    "enabled": false,
                    "clause": "before",
                    "value": null
                },
                "is_featured": {
                    "enabled": false,
                    "clause": "is_true",
                    "value": null
                }
            },
            "columns": {
                "name": true,
                "amount": true,
                "status": true
            },
            "page": 1,
            "perPage": 1,
            "view": null,
            "pinnedColumns": {
                "left": [],
                "right": []
            },
            "cursor": null,
            "columnOrder": [
                "name",
                "amount",
                "status"
            ],
            "columnWidths": {
                "name": 240,
                "amount": 160
            }
        },
        "results": {
            "data": [
                {
                    "id": 1,
                    "name": "Alpha",
                    "status": "open",
                    "amount": 10,
                    "is_featured": false,
                    "published_at": "2025-01-10T00:00:00.000000Z",
                    "_table": {
                        "key": 1,
                        "selectable": true,
                        "url": null,
                        "columns": [],
                        "cells": {
                            "status": {
                                "variant": "success",
                                "icon": null,
                                "badgeClass": null
                            }
                        },
                        "actions": [],
                        "dataAttributes": []
                    }
                }
            ],
            "currentPage": null,
            "from": null,
            "lastPage": null,
            "links": [],
            "perPage": 1,
            "to": null,
            "total": null,
            "selectableTotal": 2,
            "hasPreviousPage": false,
            "hasNextPage": true,
            "previousCursor": null,
            "nextCursor": "eyJjb250cmFjdF90b3BpY3MubmFtZSI6IkFscGhhIiwiY29udHJhY3RfdG9waWNzLmlkIjoxLCJfcG9pbnRzVG9OZXh0SXRlbXMiOnRydWV9"
        },
        "options": {
            "debounceTime": 300,
            "perPage": [
                1,
                2
            ],
            "paginationType": "cursor",
            "reloadProps": [],
            "stickyHeader": false,
            "stickyFooter": false,
            "stickyBackdropFilter": true,
            "columnResizing": true,
            "columnReordering": true
        },
        "views": null,
        "exports": [
            {
                "key": "csv",
                "label": "Contract CSV",
                "filename": "contract-topics.csv",
                "type": "csv",
                "scope": "filtered",
                "requiresSelection": false,
                "queued": false,
                "includesSummaries": true,
                "endpoint": "/_inertia-table/exports/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzQ3Vyc29yVGFibGU/csv?signature=fc4b844deea3132f324832c3f6cc215824a7da3e94c4b06890a2524f6007f1d5",
                "meta": []
            }
        ],
        "emptyState": null,
        "summaries": {
            "amount": 30
        }
    },
    "unpaginated": {
        "schemaVersion": 2,
        "name": "contract_topics",
        "columns": [
            {
                "attribute": "name",
                "header": "Name",
                "type": "text",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 240,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "amount",
                "header": "Amount",
                "type": "numeric",
                "sortable": true,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": 160,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": {
                    "type": "sum",
                    "format": null
                },
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            },
            {
                "attribute": "status",
                "header": "Status",
                "type": "badge",
                "sortable": false,
                "toggleable": true,
                "visibleByDefault": true,
                "stickable": true,
                "sticky": false,
                "width": null,
                "minWidth": null,
                "maxWidth": null,
                "resizable": true,
                "reorderable": true,
                "summary": null,
                "alignment": "left",
                "wrap": false,
                "truncate": null,
                "tooltip": null,
                "headerClass": null,
                "cellClass": null,
                "meta": []
            }
        ],
        "filters": [
            {
                "attribute": "status",
                "label": "Status",
                "clauses": [
                    "in",
                    "not_in",
                    "equals",
                    "not_equals"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "set",
                "options": [
                    {
                        "value": "open",
                        "label": "Open"
                    },
                    {
                        "value": "closed",
                        "label": "Closed"
                    }
                ],
                "multiple": true
            },
            {
                "attribute": "amount",
                "label": "Amount",
                "clauses": [
                    "equals",
                    "not_equals",
                    "greater_than",
                    "greater_than_or_equal",
                    "less_than",
                    "less_than_or_equal",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "numeric",
                "options": []
            },
            {
                "attribute": "published_at",
                "label": "Published at",
                "clauses": [
                    "before",
                    "after",
                    "equal_or_before",
                    "equal_or_after",
                    "equals",
                    "not_equals",
                    "between",
                    "not_between"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "date",
                "options": []
            },
            {
                "attribute": "is_featured",
                "label": "Featured",
                "clauses": [
                    "is_true",
                    "is_false"
                ],
                "meta": [],
                "hasDefaultValue": false,
                "showClause": true,
                "compactDisplayLabel": null,
                "type": "boolean",
                "options": []
            }
        ],
        "actions": [
            {
                "key": "archive",
                "label": "Archive",
                "scope": "bulk",
                "authorized": true,
                "disabled": false,
                "hidden": false,
                "variant": "default",
                "icon": null,
                "labelHidden": false,
                "tooltip": null,
                "buttonClass": null,
                "disabledTooltip": null,
                "confirmation": null,
                "endpoint": {
                    "method": "post",
                    "url": "/contract-topics/archive"
                },
                "meta": []
            }
        ],
        "search": [
            "name"
        ],
        "capabilities": {
            "searchable": true,
            "selectable": true,
            "paginated": false,
            "hasSearch": true,
            "hasFilters": true,
            "hasActions": true,
            "hasBulkActions": true,
            "hasExports": true,
            "hasToggleableColumns": true,
            "hasStickableColumns": true,
            "hasResizableColumns": true,
            "hasReorderableColumns": true,
            "hasSummaries": true,
            "hasEmptyState": false
        },
        "state": {
            "search": "",
            "sort": "name",
            "filters": {
                "status": {
                    "enabled": false,
                    "clause": "in",
                    "value": null
                },
                "amount": {
                    "enabled": false,
                    "clause": "equals",
                    "value": null
                },
                "published_at": {
                    "enabled": false,
                    "clause": "before",
                    "value": null
                },
                "is_featured": {
                    "enabled": false,
                    "clause": "is_true",
                    "value": null
                }
            },
            "columns": {
                "name": true,
                "amount": true,
                "status": true
            },
            "page": 1,
            "perPage": 1,
            "view": null,
            "pinnedColumns": {
                "left": [],
                "right": []
            },
            "cursor": null,
            "columnOrder": [
                "name",
                "amount",
                "status"
            ],
            "columnWidths": {
                "name": 240,
                "amount": 160
            }
        },
        "results": {
            "data": [
                {
                    "id": 1,
                    "name": "Alpha",
                    "status": "open",
                    "amount": 10,
                    "is_featured": false,
                    "published_at": "2025-01-10T00:00:00.000000Z",
                    "_table": {
                        "key": 1,
                        "selectable": true,
                        "url": null,
                        "columns": [],
                        "cells": {
                            "status": {
                                "variant": "success",
                                "icon": null,
                                "badgeClass": null
                            }
                        },
                        "actions": [],
                        "dataAttributes": []
                    }
                },
                {
                    "id": 2,
                    "name": "Beta",
                    "status": "closed",
                    "amount": 20,
                    "is_featured": true,
                    "published_at": "2025-02-20T00:00:00.000000Z",
                    "_table": {
                        "key": 2,
                        "selectable": true,
                        "url": null,
                        "columns": [],
                        "cells": {
                            "status": {
                                "variant": "success",
                                "icon": null,
                                "badgeClass": null
                            }
                        },
                        "actions": [],
                        "dataAttributes": []
                    }
                }
            ],
            "currentPage": 1,
            "from": 1,
            "lastPage": 1,
            "links": [],
            "perPage": 2,
            "to": 2,
            "total": 2,
            "selectableTotal": 2,
            "hasPreviousPage": false,
            "hasNextPage": false,
            "previousCursor": null,
            "nextCursor": null
        },
        "options": {
            "debounceTime": 300,
            "perPage": [
                1,
                2
            ],
            "paginationType": "full",
            "reloadProps": [],
            "stickyHeader": false,
            "stickyFooter": false,
            "stickyBackdropFilter": true,
            "columnResizing": true,
            "columnReordering": true
        },
        "views": null,
        "exports": [
            {
                "key": "csv",
                "label": "Contract CSV",
                "filename": "contract-topics.csv",
                "type": "csv",
                "scope": "filtered",
                "requiresSelection": false,
                "queued": false,
                "includesSummaries": true,
                "endpoint": "/_inertia-table/exports/TXVzaW5nXEluZXJ0aWFUYWJsZVxUZXN0c1xTdXBwb3J0XENvbnRyYWN0VG9waWNzVW5wYWdpbmF0ZWRUYWJsZQ/csv?signature=9391c19a55a75e2654671e53f99b820bdcc22593a6913802a9b9f5688e3d16eb",
                "meta": []
            }
        ],
        "emptyState": null,
        "summaries": {
            "amount": 30
        }
    }
} satisfies Record<
    "full" | "simple" | "cursor" | "unpaginated",
    TableResource<ContractTopic>
>;

export const contractResource = resources.full;
export const contractSimpleResource = resources.simple;
export const contractCursorResource = resources.cursor;
export const contractUnpaginatedResource = resources.unpaginated;